plugins {
    application

    id("net.neoforged.gradle.common") version "7.1.26"
}

val minecraftVersion = "26.2"
group = "dev.jsinco.brewery.recipes.datagenerator"
version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://maven.neoforged.net/releases")
}

dependencies {
    implementation("net.minecraft:client:$minecraftVersion:client-extra")
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("org.jspecify:jspecify:1.0.0")
}

java.toolchain {
    languageVersion = JavaLanguageVersion.of(21)
}

tasks {
    application {
        mainClass = "dev.jsinco.brewery.datagenerator.DataGenerator"
    }

    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("src/autogenerated/resources").absolutePath)
        jvmArgs("-Dminecraft.version=$minecraftVersion")
    }
}